### ISSUE TITLE
The pull request #21 has broken dragonegg

### ISSUE THREAD

**Issue by ianamason** [travitch/whole-program-llvm#23]
So I filed this as a comment to the closed pull request yesterday, but maybe that is a no-no.
So here it is again.  @BenjaminSchubert.

I'm trying to configure httpd-2.4.12 on ubuntu 12.04 as part of a travis ci test script.
It configures just fine if I roll back to d066aae347b8628ade80feaff8d156f1dfc60d50

But #21 breaks it:

```
configure:5285: checking whether the C compiler works
configure:5307: wllvm   -pthread   -DLINUX -D_REENTRANT -D_GNU_SOURCE   conftest.c  >&5
Traceback (most recent call last):
  File "/home/vagrant/whole-program-llvm/driver/as", line 15, in <module>
    from .utils import *
ValueError: Attempted relative import in non-package
WARNING:Failed to generate bitcode ".conftest.o.bc" for "conftest.c"
configure:5311: $? = 1
configure:5349: result: no

```

**Comment by ianamason** [comment]
Mind you it doesn't compile in either version due to:

```
Traceback (most recent call last):
  File "/vagrant/whole-program-llvm/wllvm", line 21, in <module>
    buildAndAttachBitcode(builder)
  File "/vagrant/whole-program-llvm/driver/utils.py", line 660, in buildAndAttachBitcode
    bcFile =  builder.getBitcodeFileName(af)
AttributeError: 'DragoneggBuilder' object has no attribute 'getBitcodeFileName'
```

Seems like the dragonegg approach needs some TLC @travitch? If
we want to maintain it  we should fix it I guess.  What say you Tristan?

**Comment by travitch** [comment]
I'll probably have to take a look at dragonegg.  Do you guys use dragonegg at all?  It seems like development on dragonegg has stopped and the latest version works with llvm 3.3.

At the very least, it probably isn't a path forward for anyone.  If people are using dragonegg with these scripts, I'll do my best to fix it.  Otherwise, maybe we should not bend over backwards to accommodate it.

**Comment by delcypher** [comment]
@travitch I don't use dragonegg. The project looks a little dead so it would probably make sense to remove support for it.

**Comment by ianamason** [comment]
No we don't use dragonegg. In fact we have never used it. I was just trying my hand at travis ci.

**Comment by BenjaminSchubert** [comment]
@ianamason Oh, sorry about that. If support for dragonegg is continued, I will fix it asap. Otherwise, clang version should work correctly !

@travitch I do not use dragonegg either

**Comment by delcypher** [comment]
Actually I take back what I said DragonEgg doesn't look dead. The website info might be out of date but a DragonEgg release was made for LLVM 3.6 and the README says it supports gcc 4.8 which is fairly recent.

**Comment by BenjaminSchubert** [comment]
Is this still actual @ianamason ?

**Comment by ianamason** [comment]
Your part, @BenjaminSchubert,   is fixed, my part is fixed too but sitting idle as a  pull request. Not sure if @travitch has issues with it or not. Time will tell.
